logging:
  level:
    org.springframework.web: ERROR
    openu.Medfind: DEBUG

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: medfind.alerts@gmail.com
    password: hrtcksfzgtdiakjn
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  web:
    resources:
      static-locations: "classpath:/static/client/build/"
  mvc:
    static-path-pattern: "/**"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://medfind.mysql.database.azure.com:3306/med_data?useSSL=true
    username: medlink_super
    password: Secret_Something

server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: build/.keyStore/key.cert
    key-store-password: SecretP4ss
  max-http-header-size: 10000000

medfind:
  alerts:
    appid: 577a3ade-c29c-434b-8c12-ee8749ed6dfb
    authtoken: OTgxNzVjNTUtNTU3Yi00OTUyLThhYzMtMGY3ZjBhNjRlYjM3
