logging:
  level:
    org.springframework.web: ERROR
    openu.Medfind: DEBUG

spring:
  web:
    resources:
      static-locations: "classpath:/static/client/build/"
  mvc:
    static-path-pattern: "/**"
